CREATE TABLE PROC_AUDT_DETLS_REMT_1
(
    SEQUENCE_NUMBER      NUMBER(12) ,
    ORIGIN           VARCHAR2(4),
    APPLMNEM         VARCHAR2(4),
    CURR_DATE        DATE,
    REC_TYP          VARCHAR2(4),
    CONCAT_KEY       VARCHAR2(14),
    RSRVD_DATA       NUMBER(5),
    LAST_UPDT_DTTM   DATE,
    FUNC_CODE        VARCHAR2(2) ,
    FUNC_OPID        VARCHAR2(9),
    FUNC_RLSE_IND    VARCHAR2(1)
    );
